/**
 * Pure OpenAPI → TypeScript emitter for the shared API contract.
 *
 * The generated `schemas.ts` is committed and covered by the drift gate
 * (Master Plan §7.1 G-7, ADR-001), so the emitter must be deterministic: same
 * document in, same bytes out, every run. It takes no config, touches no file
 * system, and depends on nothing but plain string work — the CLI wraps it with
 * the repository's prettier rules so the committed bytes match a fresh
 * regeneration exactly.
 */

export type EmitSchemaRef = { $ref: string };

export interface EmitSchemaProperty {
  type?: 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object';
  enum?: ReadonlyArray<string | number>;
  items?: EmitSchemaRef | { type: 'string' };
  additionalProperties?: EmitSchemaRef | { type: 'string' };
  $ref?: string;
}

export interface EmitSchema {
  type?: string;
  properties?: Readonly<Record<string, EmitSchemaProperty>>;
  required?: ReadonlyArray<string>;
}

/** The slice of an OpenAPI document the emitter reads. */
export interface EmitDocument {
  openapi: string;
  info: { title: string; version: string };
  components?: { schemas?: Readonly<Record<string, EmitSchema>> };
}

const HEADER = `/*
 * Generated by the My Shop contract tooling from the backend's OpenAPI document.
 * Do not hand-edit. Regenerate with \`npm run contracts:generate\`; CI fails the
 * drift gate (\`contracts:check\`) when this file disagrees with the backend
 * (Master Plan §7.1 G-7, ADR-001).
 */`;

/** The TypeScript name a `#/components/schemas/<name>` reference resolves to. */
function schemaName(ref: string): string {
  const name = ref.slice(ref.lastIndexOf('/') + 1);
  if (!/^[A-Za-z_$][\w$]*$/.test(name)) {
    throw new Error(`unsafe schema reference: ${ref}`);
  }
  return name;
}

function itemsType(items: EmitSchemaProperty['items']): string {
  if (items === undefined) {
    return 'unknown';
  }
  if ('$ref' in items) {
    return `readonly ${schemaName(items.$ref)}[]`;
  }
  return items.type === 'string' ? 'readonly string[]' : 'readonly unknown[]';
}

function additionalType(additional: EmitSchemaProperty['additionalProperties']): string {
  if (additional === undefined) {
    return 'object';
  }
  if ('$ref' in additional) {
    return `Readonly<Record<string, ${schemaName(additional.$ref)}>>`;
  }
  return additional.type === 'string' ? 'Readonly<Record<string, string>>' : 'object';
}

/** The TypeScript type annotation for one schema property. */
export function propertyType(prop: EmitSchemaProperty): string {
  if (prop.$ref !== undefined) {
    return schemaName(prop.$ref);
  }
  const enumValues = prop.enum;
  if (enumValues !== undefined && enumValues.length > 0) {
    return enumValues.map((value) => (typeof value === 'number' ? `${value}` : `'${value}'`)).join(' | ');
  }
  switch (prop.type) {
    case 'string':
      return 'string';
    case 'boolean':
      return 'boolean';
    case 'integer':
    case 'number':
      return 'number';
    case 'array':
      return itemsType(prop.items);
    case 'object':
      return additionalType(prop.additionalProperties);
    default:
      return 'unknown';
  }
}

/** Render the TypeScript module for a document. Deterministic by construction. */
export function emit(document: EmitDocument): string {
  const schemas = document.components?.schemas ?? {};
  const lines: string[] = [HEADER];
  const entries = Object.entries(schemas).sort(([a], [b]) => a.localeCompare(b));
  for (const [name, schema] of entries) {
    const required = new Set(schema.required ?? []);
    lines.push('');
    lines.push(`/** OpenAPI schema \`${name}\` (Master Plan §7.1, ADR-001). */`);
    lines.push(`export interface ${name} {`);
    for (const [member, prop] of Object.entries(schema.properties ?? {})) {
      const optional = required.has(member) ? '' : '?';
      lines.push(`  readonly ${member}${optional}: ${propertyType(prop)};`);
    }
    lines.push('}');
  }
  lines.push('');
  return lines.join('\n');
}
