/**
 * OpenAPI document builder tests (Master Plan §36.2 contract row).
 *
 * The document is generated from the real module graph, so "response shape matches
 * the generated contract" is asserted here at 100% of the existing surface: the
 * schemas in `components.schemas` are the classes the handlers actually return.
 *
 * Determinism of the source of truth matters more than it usually does: the drift
 * gate (G-7) compares regenerated bytes with the committed `openapi.json`, so a
 * build that shuffled properties or depended on wall-clock time would fail the gate
 * on every honest regeneration. The JSON round-trip below both asserts deep equality
 * and proves the document is serializable.
 */

import type { OpenAPIObject, ReferenceObject, SchemaObject } from '@nestjs/swagger';
import { ERROR_CODES } from '../errors/problem';
import { OPENAPI_DESCRIPTION, OPENAPI_TITLE, OPENAPI_VERSION, openapiDocument } from './openapi';

type Document = OpenAPIObject;

function buildDocument(): Promise<Document> {
  // An empty environment is the deterministic worst case: no DATABASE_URL means no
  // lifecycle work at all, and logging is forced silent by the builder regardless.
  return openapiDocument({});
}

/** The concrete (non-$ref) schema registered under `name`. */
function objectSchema(name: string, document: Document): SchemaObject {
  const entry = document.components?.schemas?.[name];
  if (entry === undefined || '$ref' in entry) {
    throw new Error(`expected a concrete schema named ${name}`);
  }
  return entry;
}

/** The JSON schema declared by `path`'s GET handler for `status`. */
function pathResponseSchema(document: Document, path: string, status: string): SchemaObject | ReferenceObject {
  const response = document.paths[path]?.get?.responses[status];
  if (response === undefined || '$ref' in response) {
    throw new Error(`expected a concrete ${status} response for ${path}`);
  }
  const schema = response.content?.['application/json']?.schema;
  if (schema === undefined) {
    throw new Error(`expected an application/json schema for ${path} ${status}`);
  }
  return schema;
}

/** One concrete property of a concrete schema; throws rather than returns undefined. */
function prop(owner: SchemaObject, key: string): SchemaObject {
  const value = owner.properties?.[key];
  if (value === undefined || '$ref' in value) {
    throw new Error(`expected a concrete property ${key}`);
  }
  return value;
}

describe('OpenAPI document builder', () => {
  it('describes the API surface with a deterministic info block', async () => {
    const document = await buildDocument();

    expect(document.openapi).toBe('3.0.0');
    expect(document.info.title).toBe(OPENAPI_TITLE);
    expect(document.info.version).toBe(OPENAPI_VERSION);
    expect(document.info.description).toBe(OPENAPI_DESCRIPTION);
  });

  it('documents /healthz with the liveness report schema', async () => {
    const document = await buildDocument();

    expect(document.paths['/healthz']?.get?.operationId).toBeDefined();
    expect(pathResponseSchema(document, '/healthz', '200')).toEqual({ $ref: '#/components/schemas/LivenessReport' });

    const liveness = objectSchema('LivenessReport', document);
    expect(liveness.type).toBe('object');
    expect(liveness.required).toEqual(['status']);
    expect(prop(liveness, 'status').enum).toEqual(['ok']);
  });

  it('documents /readyz with both answer statuses and the readiness report schema', async () => {
    const document = await buildDocument();

    for (const status of ['200', '503']) {
      expect(pathResponseSchema(document, '/readyz', status)).toEqual({
        $ref: '#/components/schemas/ReadinessReport',
      });
    }
  });

  it('describes the readiness report and its checks map', async () => {
    const document = await buildDocument();

    const report = objectSchema('ReadinessReport', document);
    expect(report.type).toBe('object');
    expect(report.required).toEqual(['ready', 'checks']);
    expect(prop(report, 'ready').type).toBe('boolean');

    const checks = prop(report, 'checks');
    expect(checks.type).toBe('object');
    expect(checks.additionalProperties).toEqual({ $ref: '#/components/schemas/ReadinessDetail' });

    const detail = objectSchema('ReadinessDetail', document);
    expect(detail.required).toEqual(['ok']);
    expect(prop(detail, 'ok').type).toBe('boolean');
    expect(prop(detail, 'reason').type).toBe('string');
  });

  it('generates the complete problem document schema from the single source of truth', async () => {
    const document = await buildDocument();

    const problem = objectSchema('ProblemDocument', document);
    expect(problem.type).toBe('object');
    expect(problem.required).toEqual(['type', 'title', 'status', 'code', 'detail', 'instance', 'traceId']);

    expect(prop(problem, 'type').type).toBe('string');
    expect(prop(problem, 'title').type).toBe('string');
    expect(prop(problem, 'status').type).toBe('integer');
    expect(prop(problem, 'detail').type).toBe('string');
    expect(prop(problem, 'instance').type).toBe('string');
    expect(prop(problem, 'traceId').type).toBe('string');

    const code = prop(problem, 'code');
    expect(code.type).toBe('string');
    expect([...(code.enum ?? [])]).toEqual([...Object.values(ERROR_CODES)]);

    const errors = prop(problem, 'errors');
    expect(errors.type).toBe('array');
    expect(errors.items).toEqual({ $ref: '#/components/schemas/ProblemFieldError' });

    const fieldError = objectSchema('ProblemFieldError', document);
    expect(fieldError.required).toEqual(['field', 'messages']);
    expect(prop(fieldError, 'field').type).toBe('string');
    expect(prop(fieldError, 'messages').type).toBe('array');
    expect(prop(fieldError, 'messages').items).toEqual({ type: 'string' });
  });

  it('is deterministic across independent builds', async () => {
    const [first, second] = await Promise.all([buildDocument(), buildDocument()]);

    expect(JSON.parse(JSON.stringify(first))).toEqual(JSON.parse(JSON.stringify(second)));
  });

  it('serializes without leaking environment material', async () => {
    // §13.1/§13.6: a document produced from a decorated source must not carry a
    // credential-shaped value out of whatever environment happened to be set.
    const document = await buildDocument();
    const serialized = JSON.stringify(document);

    expect(serialized).not.toMatch(/postgres(?:ql)?:\/\//);
    expect(serialized).not.toContain('secret');
  });
});
